export interface WordList {
  scientific: string[];
  common: string[];
  anatomy: string[];
  habitat: string[];
  behavior: string[];
  connectors: string[];
}

export const words: WordList = {
  scientific: [
    "rana",
    "bufo",
    "hyla",
    "dendrobates",
    "phyllobates",
    "litoria",
    "agalychnis",
    "bombina",
    "xenopus",
    "pipa",
    "leptodactylus",
    "eleutherodactylus",
    "rhinella",
    "duttaphrynus",
    "scaphiopus",
    "gastrophryne",
    "breviceps",
    "ceratophrys",
    "telmatobius",
    "pseudacris",
    "osteopilus",
    "smilisca",
    "trachycephalus",
    "mantella",
    "atelopus",
    "nyctibatrachus",
    "megophrys",
    "proceratophrys",
    "theloderma",
    "rhacophorus",
    "polypedates",
    "boophis",
    "heterixalus",
    "hemisus",
    "kassina",
    "hyperolius",
    "leptopelis",
    "conraua",
    "petropedetes",
    "calyptocephalella",
  ],

  common: [
    "bullfrog",
    "treefrog",
    "toadlet",
    "spring peeper",
    "wood frog",
    "coqui",
    "glass frog",
    "poison dart frog",
    "tomato frog",
    "pacman frog",
    "reed frog",
    "rain frog",
    "spadefoot",
    "horned frog",
    "leopard frog",
    "pickerel frog",
    "chorus frog",
    "cricket frog",
    "green frog",
    "golden toad",
    "fire-bellied toad",
    "midwife toad",
    "cane toad",
    "natterjack",
    "common toad",
    "clawed frog",
    "goliath frog",
    "red-eyed treefrog",
    "waxy monkey frog",
    "flying frog",
    "burrowing toad",
    "narrow-mouthed frog",
    "foam-nest frog",
    "puddle frog",
    "painted frog",
    "marsh frog",
    "edible frog",
    "pool frog",
    "amazon milk frog",
    "african dwarf frog",
  ],

  anatomy: [
    "webbed",
    "tympanum",
    "dorsal",
    "ventral",
    "glandular",
    "parotoid",
    "cloaca",
    "toe pad",
    "vocal sac",
    "nictitating membrane",
    "permeable",
    "cutaneous",
    "tubercle",
    "cranial crest",
    "snout",
    "hindlimb",
    "forelimb",
    "pelvic",
    "digit",
    "adhesive",
    "granular",
    "smooth-skinned",
    "warty",
    "speckled",
    "mottled",
    "banded",
    "striped",
    "spotted",
    "translucent",
    "iridescent",
    "pigmented",
    "keratinized",
    "elongated",
    "stout",
    "flattened",
    "robust",
    "diminutive",
    "slender",
    "squat",
    "muscular",
  ],

  habitat: [
    "riparian",
    "vernal pool",
    "ephemeral pond",
    "canopy",
    "understory",
    "leaf litter",
    "bromeliad",
    "montane",
    "tropical",
    "temperate",
    "wetland",
    "marsh",
    "swamp",
    "bog",
    "fen",
    "streamside",
    "arboreal",
    "terrestrial",
    "fossorial",
    "aquatic",
    "semiaquatic",
    "neotropical",
    "substrate",
    "microhabitat",
    "phytotelmata",
    "seep",
    "floodplain",
    "estuary",
    "mangrove",
    "cloud forest",
    "rainforest",
    "savanna",
    "woodland",
    "meadow",
    "creek",
    "riverbank",
    "pond margin",
    "mudflat",
    "moss bed",
    "rock crevice",
  ],

  behavior: [
    "amplexus",
    "metamorphosis",
    "tadpole",
    "froglet",
    "estivation",
    "hibernation",
    "brumation",
    "calling",
    "chorusing",
    "oviposition",
    "spawn",
    "clutch",
    "larval",
    "neotenic",
    "advertisement call",
    "territorial",
    "nocturnal",
    "diurnal",
    "crepuscular",
    "migration",
    "dispersal",
    "philopatric",
    "aposematic",
    "cryptic",
    "basking",
    "thermoregulation",
    "toxin",
    "alkaloid",
    "bufotoxin",
    "tetrodotoxin",
    "sequestration",
    "predation",
    "foraging",
    "ambush",
    "tongue projection",
    "hydration",
    "desiccation",
    "respiration",
    "cutaneous exchange",
    "vocalization",
  ],

  connectors: [
    "the",
    "a",
    "of",
    "and",
    "in",
    "with",
    "from",
    "near",
    "upon",
    "beneath",
    "among",
    "across",
    "through",
    "along",
    "between",
    "within",
    "during",
    "after",
    "before",
    "toward",
    "under",
    "over",
    "beside",
    "into",
    "onto",
    "around",
    "is",
    "are",
    "was",
    "were",
    "has",
    "have",
    "emerges",
    "dwells",
    "inhabits",
    "requires",
    "produces",
    "secretes",
    "displays",
    "exhibits",
    "prefers",
    "occupies",
    "generates",
    "develops",
    "adapts",
    "thrives",
    "persists",
    "resonates",
    "vibrates",
    "absorbs",
  ],
};
